### ISSUE TITLE
Problem when setting one of the two TexFields to 'Secure Text Entry'

### ISSUE THREAD

**Issue by s1m-0n** [IdleHandsApps/IHKeyboardAvoiding#11]
If you are setting one of the two TextFields to "Secure Text Entry" in the Interface Builder as it is supposed for a password field, the scrolling does not work correctly any more. Didn't this bug also occur in your demo that shows the gif animation? Do you have a workaround?

**Comment by fraserscottmorrison** [comment]
Hi Simon,

What is the actual behaviour? And what behaviour do you expect?

Fraser

**Comment by s1m-0n** [comment]
The view is moving to the top of the screen if you enable the "Secure Text Entry". You can reproduce this easily if you set the "Secure Text Entry" in the demo app for one TextField...Hopefully you can reproduce it and maybe already have a solution for this :)

**Comment by fraserscottmorrison** [comment]
Those are some pretty unhelpful bug descriptions - you wouldn’t make a good QA ;)

I figured out how to reproduce your issue: first you have to tap on a secure text field to trigger the avoiding, then you need to tap on a non secure one (spell check must be enabled too), iOS8 only.

I’ll be able to fix it but not sure when I’ll have the time. If you sort a fix yourself, I can pull in your changes

Thanks for raising this
Fraser

**Comment by s1m-0n** [comment]
Ok, the description was really not a "description" :D - sorry for that!
If I have time I'll have a more detailed look into that. I think it has to do something with the predictive Keyboard but I'm not sure with that...

**Comment by fraserscottmorrison** [comment]
np:)

Yeah it looks like when it changes from secure keyboard to predictive keyboard, I need to translate the height difference instead of the full keyboard height

**Comment by fraserscottmorrison** [comment]
Maybe the fix is in this guys fork https://github.com/ikesyo/IHKeyboardAvoiding/commit/d94e0319567f7f128eeca997de6fe7c024d7801d

**Comment by s1m-0n** [comment]
Perfect! The fork fixes the bug - can you merge it into the your master and create a new pod release? I would do the merge on my own but I have no idea how cherry-pickin works with github and forks :)
Thanks a lot!

**Comment by fraserscottmorrison** [comment]
Cool - I’ll try to do it this week

**Comment by s1m-0n** [comment]
Perfekt! Thanks!

**Comment by fraserscottmorrison** [comment]
Procrastinating done - Ive pushed the fix, and a couple of other minor fixes and bumped the pod spec version.

Let me know if it looks hunky-dory

Cheers
Fraser

**Comment by s1m-0n** [comment]
updated the pod  - works fine now! Thanks for fixing this so fast!

Cheers,
Simon
