### ISSUE TITLE
issue for swiftkey keyboard present on textview

### ISSUE THREAD

**Issue by dhanrajp4u** [IdleHandsApps/IHKeyboardAvoiding#14]
Hi, This library working good in default keyboard.
But for custom keyboard like swiftkey keyboard have issue . Added a some extra space on bottom textview.
Added some extra space on textview.
I have added image for that iPhone 5s with iOS8.2
Please, help for this.
Thanks in advance.
![img_0709](https://cloud.githubusercontent.com/assets/1658151/7449611/d568be6e-f257-11e4-9f31-6d4fded4243f.PNG)
![img_0711](https://cloud.githubusercontent.com/assets/1658151/7449610/d49ad9d6-f257-11e4-955f-57d44952a526.PNG)

**Comment by fraserscottmorrison** [comment]
Ive been going round in circles with keyboard height changes... SwiftKey and Swype are sending some weird keyboard height change notifications. Im handling it now on iPhone (but it could still be an issue on iPad as my library thinks these keyboards are being split/undocked).

Just pushed out an update, 2.2, and changing between SwiftKey, Swipe, Standard, Emoji and some other keyboards all works well now.

Thanks for raising this!
F

**Comment by fraserscottmorrison** [comment]
Im gonna assume this is resolved and close the bug - if you still have issues, reopen or raise a new issue
