### ISSUE TITLE
it seems not working in Xcode7, iPhone4S and iOS9

### ISSUE THREAD

**Issue by litt1e-p** [IdleHandsApps/IHKeyboardAvoiding#19]
it seems not working in Xcode7, iPhone4S and iOS9. though it works well in Xcode7, iphone6s

**Comment by fraserscottmorrison** [comment]
I don't have a physical iPhone4S, but its working fine in the simulator. Cant imagine why one device would behave differently to another, except that your layout will be slightly different.

Have you tried putting a breakpoint in IHKeyboardAvoiding to see why its not being triggered?

**Comment by litt1e-p** [comment]
it does triggered, but has wrong position, I use it in the simulator too. in my viewDidLoad:[IHKeyboardAvoiding setAvoidingView:self.view];
after run, my view jump down and up so werid. do I write wrong?

**Comment by fraserscottmorrison** [comment]
Are you using cocoa pods? I just pushed v 2.5 out yesterday which include a bug fix for a jumping issue. Try updating and let me know if it helps

**Comment by litt1e-p** [comment]
yeah, but I use pod search , it still 'IHKeyboardAvoiding', '~> 2.4'.

**Comment by fraserscottmorrison** [comment]
Not sure what pod search is, but 2.5 is definitely available 
http://cocoadocs.org/docsets/IHKeyboardAvoiding/2.5/

**Comment by litt1e-p** [comment]
my cocapods can search 2.5 only, I use it with MacBookPro, OC

**Comment by litt1e-p** [comment]
sorry, my mistake, my cocapods is so old, I can pod search IHKeyboardAvoiding 2.5 after update it
