### ISSUE TITLE
Doesn't do anything in iOS10

### ISSUE THREAD

**Issue by dmdque** [IdleHandsApps/IHKeyboardAvoiding#23]
I'm using Xcode 8, Swift 3, and iOS10.

`IHKeyboardAvoiding.setAvoiding(inputContainer)` has no effect. I've set a breakpoint to ensure that the line is being executed.

**Comment by fraserscottmorrison** [comment]
Works fine for me on iOS 10. Are you still having an issue?

**Comment by dmdque** [comment]
Nope, I have it working. Thanks.
