### ISSUE TITLE
Avoiding view + keyboard height bigger than screen

### ISSUE THREAD

**Issue by sagits** [IdleHandsApps/IHKeyboardAvoiding#27]
Hi, i have a UIView with 8 UITextField plus some buttons below. I have managed to make the view i want visible using the:

````
func textFieldDidBeginEditing(_ textField: UITextField) {
        
        IHKeyboardAvoiding.setAvoiding(textField.superview!, withTriggerView: textField)
}
````

Now, when editing a UITextField and clicking on next, it ll automatically scroll to the next. But is there any other way to be able to select the next UITextField (its below the keyboard before i press next), maybe using a scrollview? Thanks in advance.

**Comment by fraserscottmorrison** [comment]
Theres no way to do this currently, but it mightn't be too hard to add. Feel free to add it yourself and give me a PR. I might have time to work on it myself, but I don't know when

**Comment by fraserscottmorrison** [comment]
Ive just done some testing around this, and IHKeyboardAvoiding does handle the situation where a user taps return and a UITextField thats under the keyboard is focused.

Are you changing the first responder in textFieldShouldReturn?
```swift
    public func textFieldShouldBeginEditing(_ textField: UITextField) -> Bool {
        KeyboardAvoiding.avoidingView = textField.superview!
        return true
    }
    
    public func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        if textField == self.textField1 {
            self.textField2.becomeFirstResponder()
        }
        return true
    }
```
