### ISSUE TITLE
Swift 3.0 setting the avoidingview to self when self is still nil crash

### ISSUE THREAD

**Issue by Tripwire999** [IdleHandsApps/IHKeyboardAvoiding#28]
Hi,

I've updated the version of IHKeyboardAvoiding to the latest Swift version. When executing the following code:
`KeyboardAvoiding.avoidingView = self`

And executing this in an AwakeFromNib which isn't showing itself yet (it's a popup which will show when pressing a button) it will crash saying the following:
fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by fraserscottmorrison** [comment]
In Objective C, when an object is nil, any method calls are ignored, but in Swift an exception is thrown.

I don't think I can fix IHKeyboarding entirely, but I can stop it from crashing - know which line it crashes on?

I think you'll have to change you code to call KeyboardAvoiding.avoidingView = self.cell.view in the ViewController instead

**Comment by Tripwire999** [comment]
Hi,

The line it crashes is in KeyboardAvoiding.swift on line 245:

> self.avoidingViewUsesAutoLayout = avoidingView != nil ? avoidingView!.superview!.constraints.count > 0 : false

**Comment by fraserscottmorrison** [comment]
Ah Im checking if the avoidingView is nil but not it's superview.  I'll have a quick look into it

**Comment by fraserscottmorrison** [comment]
Ok so checking if the superview != nil should fix the crash

self.avoidingViewUsesAutoLayout = (avoidingView != nil && avoidingView!.superview != nil) ? avoidingView!.superview!.constraints.count > 0 : false

But I don't know how to test your exact situation

I'd suggest not setting the avoidingView until its been added to the view hierarchy
