### ISSUE TITLE
self.avoidingViewUsesAutoLayout = avoidingView != nil ? avoidingView!.superview!.constraints.count > 0 : false CRASH

### ISSUE THREAD

**Issue by pprevalon** [IdleHandsApps/IHKeyboardAvoiding#29]
I get a nil error.

fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by fraserscottmorrison** [comment]
Seems like your avoidingViews superview is nil - has it been removed from the view hierarchy?

Does changing the line to this fix it?
self.avoidingViewUsesAutoLayout = (avoidingView != nil && avoidingView!.superview != nil) ? avoidingView!.superview!.constraints.count > 0 : false
