### ISSUE TITLE
Fatal Crash if Avoiding View is Improperly Set

### ISSUE THREAD

**Issue by Marquis103** [IdleHandsApps/IHKeyboardAvoiding#30]
I caught this in a code review of someones code.  They set a view to be the avoiding view of an outlet in viewDidLoad and the code crashed.  There was a ton of force unwrapping when the app crashed.  Just passing along.  Very easy fix would be to nil coalesce the count to 0 if the avoiding view is nil.

![crashed](https://cloud.githubusercontent.com/assets/449217/22871321/d15468c4-f17d-11e6-9a60-2533c9b0aa35.png)

**Comment by fraserscottmorrison** [comment]
Hiya Marquis,

This one was fixed a couple weeks ago - the latest version, 3.7, will sort you out

Cheers
Fraser
