### ISSUE TITLE
No Scrollview required is fine, but can't use it with scrollview?

### ISSUE THREAD

**Issue by AndresCianio** [IdleHandsApps/IHKeyboardAvoiding#31]
I love the way this works, but I have some views that DO use a scrollview in order to display forms on smaller devices.

Is it possible that this component doesn't work in that case? It's working perfect for me in all other controllers, but when the controller has a main ScrollView with all the stuff inside it doesn't work.

**Comment by fraserscottmorrison** [comment]
No it won't work with scroll views. You could subscribe to keyboardDidAppear notifications and adjust the contentOffset. Or use TPKeyboardAvoiding which does that for you
