### ISSUE TITLE
Do it support auto layout?

### ISSUE THREAD

**Issue by alex-payer** [IdleHandsApps/IHKeyboardAvoiding#33]
It seems like IHKeyboardAvoiding doesn't support auto layout, it only moves KeyboardAvoiding.avoidingView up and down, which could potentially overlaps other views.
Here's what in my storyboard
<img width="351" alt="screen shot 2017-06-08 at 3 57 57 pm" src="https://user-images.githubusercontent.com/27711780/26914217-56c4bf50-4c63-11e7-9f8a-e5e862e6c537.png">

each text field has same distance from its top's, the first one is in the centre of screen. If I click text field 3, it becomes like this
![simulator screen shot 8 jun 2017 4 00 07 pm](https://user-images.githubusercontent.com/27711780/26914263-9e47520c-4c63-11e7-8ef3-d06a50962019.png)

Is there any way that I could achieve this?
![simulator screen shot 8 jun 2017 4 01 42 pm](https://user-images.githubusercontent.com/27711780/26914294-cde9ea88-4c63-11e7-81b4-0383e0c9d2e3.png)

**Comment by fraserscottmorrison** [comment]
Is TextField3 Anchored to its superview bottom?

if TextField3 is being moved correctly, why are your other constraints being broken? Are you getting any layout errors in you console?

**Comment by alex-payer** [comment]
@fraserscottmorrison now I got it, after setting bottom constraint, it works well. Does it mean that when using IHKeyboardAvoiding, it must have bottom constraint?

**Comment by fraserscottmorrison** [comment]
It needs either a bottom or top constraint. If to have a top constrain it will reduce it to move the view up. So if you want all 3 text views to move up, with a top constraint, just put them all in a container view and register the container view with IHKeyboardAvoiding
