### ISSUE TITLE
Keyboard pushing textview off screen

### ISSUE THREAD

**Issue by swiftylondon** [IdleHandsApps/IHKeyboardAvoiding#36]
When I tap on a textfield and the text filed is near the top of the screen it seems to push the text field off the screen so you can't see what you are typing. 
I would expect the text field to overlay the view so that the textfield is still visible if the view doesn't need shifting.

**Comment by fraserscottmorrison** [comment]
This library will only move the view that you set as the avoidingView. You haven't given much info but I assume you've set a parent view of the textfield as the avoidingView. 

There probably several ways to fix this by changing your layout. Maybe just take the textfield out of the avoidingView if you don't want it to move
