### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by dethell** [IdleHandsApps/IHKeyboardAvoiding#37]
I see older commits related to carthage support, but when I try to include this project in my Cartfile I just get errors that:

Dependency "IHKeyboardAvoiding" has no shared framework schemes

Is there anything that needs to be done currently to get this to work with carthage?

**Comment by fraserscottmorrison** [comment]
No idea, I don’t use Carthage. 

I’ve pulled in some PRs but I guess its broken. Feel free to submit a PR to fix
F

**Comment by dethell** [comment]
I took a shot at it, but ended up abandoning the effort due to time constraints on my current project.
