### ISSUE TITLE
Swift 4

### ISSUE THREAD

**Issue by Gerst20051** [IdleHandsApps/IHKeyboardAvoiding#41]
Any progress on updating this for Swift 4?

**Comment by Gerst20051** [comment]
Looks like this pull request may address the issues. https://github.com/IdleHandsApps/IHKeyboardAvoiding/pull/40

**Comment by fraserscottmorrison** [comment]
Ive just push out an update that makes IHKeyboardAvoiding play nice with Swift 4.

BTW its possible to build certain pods for Swift 4 and others for Swift 3.2
