### ISSUE TITLE
Control view that moved upon avoiding

### ISSUE THREAD

**Issue by happiehappie** [IdleHandsApps/IHKeyboardAvoiding#42]
I have a dummy app based on my current use case.
I need the image view to go up (it's fine if it goes below the top UIView. Just don't let the image resize when the keyboard shows.
What should I do
[TestIHImage.zip](https://github.com/IdleHandsApps/IHKeyboardAvoiding/files/1358919/TestIHImage.zip)

**Comment by happiehappie** [comment]
Solved it by changing constraints priority and set a height constraint at the appropriate timing

**Comment by fraserscottmorrison** [comment]
Sorry I couldn't look into this earlier, had some high priority stuff to deal with at work

Glad you got it sorted
Fraser
