### ISSUE TITLE
keyboard avoiding not working properly on iOS 11.2

### ISSUE THREAD

**Issue by aznelite89** [IdleHandsApps/IHKeyboardAvoiding#44]
Upon open the app in iOS 11.2, the keyboard avoiding is working. But only worked for once then the keyboard avoiding not working anymore. I checked with 11.1.1 , 11.1.2 , 11.2. It seems only happen at 11.2 devices.  ( **FYI , the issue happens when I using navigation controller and perform segue or unwind segue, after I perform one of those segues , the keyboard avoiding is not working** )

**Comment by fraserscottmorrison** [comment]
This seems to be happening all the time in iOS11.2

It must be a bug in the iOS version but Ive added a workaround (some might call it a hack) for it. Would you be able to verify the fix?

Thanks for raising it!
Fraser

**Comment by Jitenderios** [comment]
Hi fraser, There is a problem in ios 11.2, its not working. The avoiding view is not moving , its hiding behind the keyboard. I have updated to the latest keyboard avoiding library, But still facing the same issue.

**Comment by fssilva** [comment]
This hack breaks the functionality when the suggestion bar disappear after been selected. You get an empty space between the view and the keyboard.

<img width="721" alt="screen shot 2018-07-06 at 16 10 18" src="https://user-images.githubusercontent.com/589306/42383326-30e8fcec-8137-11e8-90df-8d552327ceaf.png">
