### ISSUE TITLE
swift 4.2 support 🙏

### ISSUE THREAD

**Issue by piemonte** [IdleHandsApps/IHKeyboardAvoiding#57]
great library, would be nice to have swift 4.2 support too

**Comment by Un3qual** [comment]
Until #56 gets merged, you can use `pod 'IHKeyboardAvoiding', :git => 'https://github.com/Kirow/IHKeyboardAvoiding.git', :branch => 'swift-4.2'`.

**Comment by jdrevet** [comment]
Hi @fraserscottmorrison 
Do you plan to release a new version with Swift 4.2 support ?

**Comment by fraserscottmorrison** [comment]
Hi guys, Ive merged the PR for Swift4.2

To get through cocoapod validation I also needed to update the .swift-version file to 4.2

All good now!
